Repository UMC-AboutMe/AboutMe-BE, pull requests merged in 2024-02, with the labels that each got.

#70 #66 마이스페이스 업데이트
  .DS_Store
  src/main/java/com/example/aboutme/app/controller/SpaceController.java
  src/main/java/com/example/aboutme/app/dto/SpaceRequest.java
  src/main/java/com/example/aboutme/app/dto/SpaceResponse.java
  src/main/java/com/example/aboutme/converter/SpaceConverter.java
  src/main/java/com/example/aboutme/domain/Space.java
  src/main/java/com/example/aboutme/repository/SpaceRepository.java
  src/main/java/com/example/aboutme/service/SpaceService/SpaceService.java
  src/main/java/com/example/aboutme/service/SpaceService/SpaceServiceImpl.java
  src/main/java/com/example/aboutme/validation/annotation/ExistMood.java
  src/main/java/com/example/aboutme/validation/validator/MoodExistValidator.java
Labels: ✨ feat

#73 #71 마이스페이스 일정 추가
  src/main/java/com/example/aboutme/app/controller/SpaceController.java
  src/main/java/com/example/aboutme/app/dto/PlanRequest.java
  src/main/java/com/example/aboutme/app/dto/PlanResponse.java
  src/main/java/com/example/aboutme/app/dto/SpaceResponse.java
  src/main/java/com/example/aboutme/converter/PlanConverter.java
  src/main/java/com/example/aboutme/converter/SpaceConverter.java
  src/main/java/com/example/aboutme/domain/Plan.java
  src/main/java/com/example/aboutme/domain/Space.java
  src/main/java/com/example/aboutme/repository/PlanRepository.java
  src/main/java/com/example/aboutme/service/SpaceService/SpaceService.java
  src/main/java/com/example/aboutme/service/SpaceService/SpaceServiceImpl.java
Labels: ✨ feat

#43 #33 delete the profile from storage
  src/main/java/com/example/aboutme/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/aboutme/app/controller/MemberProfileController.java
  src/main/java/com/example/aboutme/app/dto/MemberProfileRequest.java
  src/main/java/com/example/aboutme/app/dto/MemberProfileResponse.java
  src/main/java/com/example/aboutme/converter/MemberProfileConverter.java
  src/main/java/com/example/aboutme/domain/Member.java
  src/main/java/com/example/aboutme/repository/MemberProfileRepository.java
  src/main/java/com/example/aboutme/service/MemberProfileService/MemberProfileService.java
  src/main/java/com/example/aboutme/service/MemberProfileService/MemberProfileServiceImpl.java
Labels: ✨ feat

#42 #34 patchDefaultMyProfile api 구현
  src/main/java/com/example/aboutme/app/controller/ProfileController.java
  src/main/java/com/example/aboutme/app/dto/ProfileResponse.java
  src/main/java/com/example/aboutme/converter/ProfileConverter.java
  src/main/java/com/example/aboutme/domain/Profile.java
  src/main/java/com/example/aboutme/service/ProfileService/ProfileService.java
  src/main/java/com/example/aboutme/service/ProfileService/ProfileServiceImpl.java
Labels: ✨ feat

#75 #3 Kakao&Google RESTful Login 및 DB저장
  build.gradle
  src/main/java/com/example/aboutme/Login/MemberConverter.java
  src/main/java/com/example/aboutme/Login/controller/LoginController.java
  src/main/java/com/example/aboutme/Login/dto/MsgResponse.java
  src/main/java/com/example/aboutme/Login/dto/SocialInfoRequest.java
  src/main/java/com/example/aboutme/Login/jwt/JwtDTO.java
  src/main/java/com/example/aboutme/Login/jwt/TokenDTO.java
  src/main/java/com/example/aboutme/Login/jwt/TokenProvider.java
  src/main/java/com/example/aboutme/Login/service/GoogleService.java
  src/main/java/com/example/aboutme/Login/service/GoogleServiceImpl.java
  src/main/java/com/example/aboutme/Login/service/KakaoService.java
  src/main/java/com/example/aboutme/Login/service/KakaoServiceImpl.java
  src/main/java/com/example/aboutme/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/aboutme/converter/LoginConverter.java
  src/main/java/com/example/aboutme/domain/Member.java
  src/main/java/com/example/aboutme/repository/MemberRepository.java
Labels: ✨ feat

#80 #79 delete Member구현 및 Login 내부 파일 재구성
  src/main/java/com/example/aboutme/app/controller/LoginController.java
  src/main/java/com/example/aboutme/app/dto/MsgResponse.java
  src/main/java/com/example/aboutme/app/dto/SocialInfoRequest.java
  src/main/java/com/example/aboutme/converter/LoginConverter.java
  src/main/java/com/example/aboutme/converter/MemberConverter.java
  src/main/java/com/example/aboutme/service/LoginService/GoogleService.java
  src/main/java/com/example/aboutme/service/LoginService/GoogleServiceImpl.java
  src/main/java/com/example/aboutme/service/LoginService/KakaoService.java
  src/main/java/com/example/aboutme/service/LoginService/KakaoServiceImpl.java
  src/main/java/com/example/aboutme/service/MemberService/MemberService.java
  src/main/java/com/example/aboutme/service/MemberService/MemberServiceImpl.java
Labels: ✨ feat

#82 #81 Login Logic 추가
  src/main/java/com/example/aboutme/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/aboutme/app/controller/LoginController.java
  src/main/java/com/example/aboutme/app/dto/MemberProfileResponse.java
  src/main/java/com/example/aboutme/app/dto/MsgResponse.java
  src/main/java/com/example/aboutme/converter/LoginConverter.java
  src/main/java/com/example/aboutme/converter/MemberConverter.java
  src/main/java/com/example/aboutme/converter/MemberProfileConverter.java
  src/main/java/com/example/aboutme/repository/MemberRepository.java
  src/main/java/com/example/aboutme/service/LoginService/GoogleService.java
  src/main/java/com/example/aboutme/service/LoginService/GoogleServiceImpl.java
  src/main/java/com/example/aboutme/service/LoginService/KakaoService.java
  src/main/java/com/example/aboutme/service/LoginService/KakaoServiceImpl.java
  src/main/java/com/example/aboutme/service/MemberProfileService/MemberProfileServiceImpl.java
Labels: ✨ feat, 🐛 fix

#87 #86 마이스페이스 이미지 디비 저장
  src/main/java/com/example/aboutme/converter/SpaceImageConverter.java
  src/main/java/com/example/aboutme/domain/Space.java
  src/main/java/com/example/aboutme/domain/SpaceImage.java
  src/main/java/com/example/aboutme/service/SpaceService/SpaceServiceImpl.java
Labels: 🐛 fix

#88 #84 스페이스 검색 API 구현
  src/main/java/com/example/aboutme/app/controller/SpaceController.java
  src/main/java/com/example/aboutme/app/dto/SpaceResponse.java
  src/main/java/com/example/aboutme/converter/SpaceConverter.java
  src/main/java/com/example/aboutme/repository/SpaceRepository.java
  src/main/java/com/example/aboutme/service/SpaceService/SpaceService.java
  src/main/java/com/example/aboutme/service/SpaceService/SpaceServiceImpl.java
  src/main/resources/application.yml
Labels: ✨ feat

#90 #89 마이스페이스 생성 중복 확인
  src/main/java/com/example/aboutme/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/aboutme/app/controller/SpaceController.java
  src/main/java/com/example/aboutme/service/SpaceService/SpaceService.java
  src/main/java/com/example/aboutme/service/SpaceService/SpaceServiceImpl.java
Labels: ✨ feat, 🐛 fix

#74 #69 서버 로그 방식 수정
  src/main/java/com/example/aboutme/apiPayload/exception/ExceptionAdvice.java
  src/main/java/com/example/aboutme/apiPayload/exception/GeneralException.java
Labels: ♻️ refactor

#77 #76 내 마이프로필 삭제시 발생하는 에러 해결
  src/main/java/com/example/aboutme/domain/Profile.java
Labels: 🐛 fix

#94 #93 마이스페이스 멤버 FK 미설정 오류 수정
  src/main/java/com/example/aboutme/converter/SpaceConverter.java
  src/main/java/com/example/aboutme/service/SpaceService/SpaceServiceImpl.java
Labels: ✨ feat

#96 #78 내 마이프로필 이미지 수정하기 API 완료
  src/main/java/com/example/aboutme/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/aboutme/app/controller/ProfileController.java
  src/main/java/com/example/aboutme/app/dto/ProfileRequest.java
  src/main/java/com/example/aboutme/app/dto/ProfileResponse.java
  src/main/java/com/example/aboutme/converter/ProfileConverter.java
  src/main/java/com/example/aboutme/converter/ProfileImageConverter.java
  src/main/java/com/example/aboutme/domain/Profile.java
  src/main/java/com/example/aboutme/domain/ProfileImage.java
  src/main/java/com/example/aboutme/domain/constant/ProfileImageType.java
  src/main/java/com/example/aboutme/repository/ProfileImageRepository.java
  src/main/java/com/example/aboutme/service/ProfileService/ProfileService.java
  src/main/java/com/example/aboutme/service/ProfileService/ProfileServiceImpl.java
  src/main/java/com/example/aboutme/validation/annotation/CheckEnumType.java
  src/main/java/com/example/aboutme/validation/validator/EnumValidator.java
Labels: ✨ feat, 🚧 update

#95 #91 프로필 보관함 내 검색
  src/main/java/com/example/aboutme/app/controller/MemberProfileController.java
  src/main/java/com/example/aboutme/app/dto/MemberProfileResponse.java
  src/main/java/com/example/aboutme/app/dto/MemberSpaceResponse.java
  src/main/java/com/example/aboutme/converter/MemberProfileConverter.java
  src/main/java/com/example/aboutme/converter/ProfileConverter.java
  src/main/java/com/example/aboutme/repository/MemberProfileRepository.java
  src/main/java/com/example/aboutme/repository/ProfileFeatureRepository.java
  src/main/java/com/example/aboutme/service/MemberProfileService/MemberProfileService.java
  src/main/java/com/example/aboutme/service/MemberProfileService/MemberProfileServiceImpl.java
Labels: ✨ feat

#101 #100 상대방 마이프로필 조회
  src/main/java/com/example/aboutme/app/controller/ProfileController.java
  src/main/java/com/example/aboutme/service/ProfileService/ProfileService.java
  src/main/java/com/example/aboutme/service/ProfileService/ProfileServiceImpl.java
Labels: 🚧 update

#103 #92 마이프로필 검색 API 완료
  src/main/java/com/example/aboutme/app/controller/ProfileController.java
  src/main/java/com/example/aboutme/app/dto/ProfileResponse.java
  src/main/java/com/example/aboutme/converter/ProfileConverter.java
  src/main/java/com/example/aboutme/service/ProfileService/ProfileService.java
  src/main/java/com/example/aboutme/service/ProfileService/ProfileServiceImpl.java
  src/main/java/com/example/aboutme/validation/annotation/ExistProfileBySerialNum.java
  src/main/java/com/example/aboutme/validation/validator/ProfileExistBySerialNumValidator.java
Labels: ✨ feat

#99 #97/login code update
  src/main/java/com/example/aboutme/Login/jwt/TokenProvider.java
  src/main/java/com/example/aboutme/app/controller/LoginController.java
  src/main/java/com/example/aboutme/app/dto/SocialInfoRequest.java
  src/main/java/com/example/aboutme/service/LoginService/KakaoServiceImpl.java
  src/main/resources/application.yml
Labels: 🚧 update

#107 #106 내 마이프로필 상대방에게 공유하기
  src/main/java/com/example/aboutme/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/aboutme/app/controller/MemberProfileController.java
  src/main/java/com/example/aboutme/app/controller/ProfileController.java
  src/main/java/com/example/aboutme/app/dto/ProfileRequest.java
  src/main/java/com/example/aboutme/app/dto/ProfileResponse.java
  src/main/java/com/example/aboutme/converter/MemberProfileConverter.java
  src/main/java/com/example/aboutme/converter/ProfileConverter.java
  src/main/java/com/example/aboutme/domain/mapping/MemberProfile.java
  src/main/java/com/example/aboutme/repository/MemberProfileRepository.java
  src/main/java/com/example/aboutme/service/MemberProfileService/MemberProfileService.java
  src/main/java/com/example/aboutme/service/MemberProfileService/MemberProfileServiceImpl.java
Labels: ✨ feat

#111 #108 마이스페이스 공유
  src/main/java/com/example/aboutme/app/controller/SpaceController.java
  src/main/java/com/example/aboutme/app/dto/AlarmRequest.java
  src/main/java/com/example/aboutme/app/dto/AlarmResponse.java
  src/main/java/com/example/aboutme/converter/AlarmConverter.java
  src/main/java/com/example/aboutme/domain/Alarm.java
  src/main/java/com/example/aboutme/domain/Member.java
  src/main/java/com/example/aboutme/repository/AlarmRepository.java
  src/main/java/com/example/aboutme/service/AlarmService/AlarmService.java
  src/main/java/com/example/aboutme/service/AlarmService/AlarmServiceImpl.java
  src/main/java/com/example/aboutme/service/SpaceService/SpaceService.java
  src/main/java/com/example/aboutme/service/SpaceService/SpaceServiceImpl.java
  src/main/java/com/example/aboutme/validation/annotation/ExistMember.java
  src/main/java/com/example/aboutme/validation/validator/MemberExistValidator.java
Labels: ✨ feat

#115 #114 default값을 False로 하는 로직 추가
  src/main/java/com/example/aboutme/app/controller/ProfileController.java
  src/main/java/com/example/aboutme/repository/ProfileRepository.java
  src/main/java/com/example/aboutme/service/ProfileService/ProfileService.java
  src/main/java/com/example/aboutme/service/ProfileService/ProfileServiceImpl.java
Labels: ✨ feat, 🚧 update

#113 #112 마이페이지 조회 API 구현
  src/main/java/com/example/aboutme/app/controller/MyPageController.java
  src/main/java/com/example/aboutme/app/dto/MyPageResponse.java
  src/main/java/com/example/aboutme/converter/MemberConverter.java
  src/main/java/com/example/aboutme/repository/MemberProfileRepository.java
  src/main/java/com/example/aboutme/repository/MemberRepository.java
  src/main/java/com/example/aboutme/repository/MemberSpaceRepository.java
  src/main/java/com/example/aboutme/repository/ProfileFeatureRepository.java
  src/main/java/com/example/aboutme/repository/ProfileRepository.java
  src/main/java/com/example/aboutme/service/MemberService/MemberService.java
  src/main/java/com/example/aboutme/service/MemberService/MemberServiceImpl.java
Labels: ✨ feat

#129 #127 마이스페이스 jwttoken으로 변경
  src/main/java/com/example/aboutme/app/controller/SpaceController.java
  src/main/java/com/example/aboutme/repository/MemberRepository.java
  src/main/java/com/example/aboutme/service/MemberService/MemberService.java
  src/main/java/com/example/aboutme/service/MemberService/MemberServiceImpl.java
Labels: ♻️ refactor

#133 #132 - Token 만료시간 삭제
  src/main/java/com/example/aboutme/Login/jwt/TokenProvider.java
Labels: 🚧 update

#123 #122 프로필 이미지 응답값 에러 수정
  src/main/java/com/example/aboutme/converter/ProfileConverter.java
  src/main/java/com/example/aboutme/domain/ProfileImage.java
Labels: 🐛 fix

#124 MemberSpace 엔티티가 BaseEntity 미상속받던 것 수정
  src/main/java/com/example/aboutme/domain/mapping/MemberSpace.java
Labels: 🐛 fix

#121 #120 알림 데이터 조회
  src/main/java/com/example/aboutme/app/controller/AlarmController.java
  src/main/java/com/example/aboutme/app/dto/AlarmRequest.java
  src/main/java/com/example/aboutme/app/dto/AlarmResponse.java
  src/main/java/com/example/aboutme/converter/AlarmConverter.java
  src/main/java/com/example/aboutme/domain/Alarm.java
  src/main/java/com/example/aboutme/repository/AlarmRepository.java
  src/main/java/com/example/aboutme/service/AlarmService/AlarmService.java
  src/main/java/com/example/aboutme/service/AlarmService/AlarmServiceImpl.java
Labels: ✨ feat

#131 #130 즐겨찾기 우선 정렬
  src/main/java/com/example/aboutme/converter/MemberProfileConverter.java
  src/main/java/com/example/aboutme/converter/MemberSpaceConverter.java
Labels: ✨ feat

#135 #134 헤더값 변경
  src/main/java/com/example/aboutme/Login/jwt/TokenDTO.java
  src/main/java/com/example/aboutme/Login/jwt/TokenProvider.java
  src/main/java/com/example/aboutme/app/controller/LoginController.java
  src/main/java/com/example/aboutme/app/controller/MemberProfileController.java
  src/main/java/com/example/aboutme/app/controller/ProfileController.java
  src/main/java/com/example/aboutme/app/dto/MsgResponse.java
  src/main/java/com/example/aboutme/converter/LoginConverter.java
  src/main/java/com/example/aboutme/repository/MemberRepository.java
  src/main/java/com/example/aboutme/service/LoginService/GoogleServiceImpl.java
  src/main/java/com/example/aboutme/service/LoginService/KakaoServiceImpl.java
  src/main/java/com/example/aboutme/service/MemberProfileService/MemberProfileService.java
  src/main/java/com/example/aboutme/service/MemberProfileService/MemberProfileServiceImpl.java
  src/main/java/com/example/aboutme/service/MemberService/MemberService.java
  src/main/java/com/example/aboutme/service/MemberService/MemberServiceImpl.java
  src/main/java/com/example/aboutme/service/ProfileService/ProfileService.java
  src/main/java/com/example/aboutme/service/ProfileService/ProfileServiceImpl.java
Labels: 🚧 update, ♻️ refactor

#138 헤더 member-id -> token 으로 변경
  src/main/java/com/example/aboutme/app/controller/MyPageController.java
  src/main/java/com/example/aboutme/app/controller/ProfileController.java
  src/main/java/com/example/aboutme/repository/MemberRepository.java
  src/main/java/com/example/aboutme/service/MemberProfileService/MemberProfileService.java
  src/main/java/com/example/aboutme/service/MemberProfileService/MemberProfileServiceImpl.java
  src/main/java/com/example/aboutme/service/MemberService/MemberService.java
  src/main/java/com/example/aboutme/service/MemberService/MemberServiceImpl.java
  src/main/java/com/example/aboutme/service/ProfileService/ProfileService.java
  src/main/java/com/example/aboutme/service/ProfileService/ProfileServiceImpl.java
Labels: 🚧 update

#144 #143 tokenProvider 잘못된 소셜타입 리턴하던 에러 해결
  src/main/java/com/example/aboutme/Login/jwt/TokenProvider.java
  src/main/java/com/example/aboutme/service/MemberService/MemberServiceImpl.java
Labels: 🐛 fix

#146 #145 알림 데이터 삭제
  src/main/java/com/example/aboutme/Login/jwt/TokenProvider.java
  src/main/java/com/example/aboutme/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/aboutme/app/controller/AlarmController.java
  src/main/java/com/example/aboutme/app/dto/AlarmResponse.java
  src/main/java/com/example/aboutme/converter/AlarmConverter.java
  src/main/java/com/example/aboutme/service/AlarmService/AlarmService.java
  src/main/java/com/example/aboutme/service/AlarmService/AlarmServiceImpl.java
Labels: ✨ feat

#148 #147 MemberProfileController 수정
  src/main/java/com/example/aboutme/app/controller/MemberProfileController.java
Labels: ❗️HOTFIX

#150 #149 cicd 다시 배포
  .github/workflows/dev-deploy.yaml
  .platform/nginx/conf.d/client_max_body_size.conf
  src/main/resources/application.yml
Labels: 🚚 chore

#126 #125 마이스페이스 공유 닉네임으로 변경
  src/main/java/com/example/aboutme/app/controller/SpaceController.java
  src/main/java/com/example/aboutme/app/dto/AlarmResponse.java
  src/main/java/com/example/aboutme/converter/AlarmConverter.java
  src/main/java/com/example/aboutme/domain/Alarm.java
Labels: 🚧 update

#153 #152 my space share update
  src/main/java/com/example/aboutme/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/aboutme/app/controller/SpaceController.java
  src/main/java/com/example/aboutme/app/dto/SpaceRequest.java
  src/main/java/com/example/aboutme/domain/Alarm.java
  src/main/java/com/example/aboutme/repository/SpaceRepository.java
  src/main/java/com/example/aboutme/service/SpaceService/SpaceServiceImpl.java
  src/main/java/com/example/aboutme/validation/annotation/ExistSpaceNickname.java
  src/main/java/com/example/aboutme/validation/validator/SpaceNicknameExistValidator.java
Labels: 🚧 update

#155 #154 Profile casecade 설정
  src/main/java/com/example/aboutme/domain/Profile.java
Labels: ❗️HOTFIX
