Repository UMC-AboutMe/AboutMe-BE, pull requests merged in 2024-01, with the labels that each got.

#10 Feat/#4 create my space
  build.gradle
  src/main/java/com/example/aboutme/apiPayload/ApiResponse.java
  src/main/java/com/example/aboutme/apiPayload/code/BaseCode.java
  src/main/java/com/example/aboutme/apiPayload/code/BaseErrorCode.java
  src/main/java/com/example/aboutme/apiPayload/code/ErrorReasonDTO.java
  src/main/java/com/example/aboutme/apiPayload/code/ReasonDTO.java
  src/main/java/com/example/aboutme/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/aboutme/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/example/aboutme/apiPayload/exception/ExceptionAdvice.java
  src/main/java/com/example/aboutme/apiPayload/exception/GeneralException.java
  src/main/java/com/example/aboutme/apiPayload/exception/handler/SpaceHandler.java
  src/main/java/com/example/aboutme/app/controller/SpaceController.java
  src/main/java/com/example/aboutme/app/controller/TempController.java
  src/main/java/com/example/aboutme/app/dto/SpaceRequest.java
  src/main/java/com/example/aboutme/app/dto/SpaceResponse.java
  src/main/java/com/example/aboutme/app/dto/TempDto.java
  src/main/java/com/example/aboutme/converter/SpaceConverter.java
  src/main/java/com/example/aboutme/domain/Space.java
  src/main/java/com/example/aboutme/repository/SpaceRepository.java
  src/main/java/com/example/aboutme/repository/TempRepository.java
  src/main/java/com/example/aboutme/service/SpaceService/SpaceCommandService.java
  src/main/java/com/example/aboutme/service/SpaceService/SpaceCommandServiceImpl.java
  src/main/java/com/example/aboutme/service/SpaceService/SpaceQueryService.java
  src/main/java/com/example/aboutme/service/SpaceService/SpaceQueryServiceImpl.java
  src/main/java/com/example/aboutme/service/TempService.java
  src/main/java/com/example/aboutme/validation/annotation/CharacterTypeBoundary.java
  src/main/java/com/example/aboutme/validation/annotation/RoomTypeBoundary.java
  src/main/java/com/example/aboutme/validation/validator/CharacterTypeBoundaryValidator.java
  src/main/java/com/example/aboutme/validation/validator/RoomTypeBoundaryValidator.java
  src/main/resources/application.yml
Labels: ✨ feat

#15 #14 마이프로필 생성 API 구현완료
  src/main/java/com/example/aboutme/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/aboutme/app/controller/ProfileController.java
  src/main/java/com/example/aboutme/app/dto/ProfileRequest.java
  src/main/java/com/example/aboutme/app/dto/ProfileResponse.java
  src/main/java/com/example/aboutme/converter/ProfileConverter.java
  src/main/java/com/example/aboutme/converter/ProfileFeatureConverter.java
  src/main/java/com/example/aboutme/domain/Profile.java
  src/main/java/com/example/aboutme/domain/ProfileFeature.java
  src/main/java/com/example/aboutme/repository/MemberRepository.java
  src/main/java/com/example/aboutme/repository/ProfileRepository.java
  src/main/java/com/example/aboutme/service/MemberService/MemberService.java
  src/main/java/com/example/aboutme/service/MemberService/MemberServiceImpl.java
  src/main/java/com/example/aboutme/service/ProfileService/ProfileService.java
  src/main/java/com/example/aboutme/service/ProfileService/ProfileServiceImpl.java
Labels: ✨ feat

#22 #19 cicd
  .ebextensions-dev/00-markFiles.config
  .ebextensions-dev/01-set-timezone.config
  .github/workflows/dev-deploy.yaml
  .platform/nginx.conf
  Procfile
  build.gradle
Labels: 🚚 chore

#24 #22 마이스페이스 조회
  src/main/java/com/example/aboutme/app/controller/SpaceController.java
  src/main/java/com/example/aboutme/app/dto/SpaceResponse.java
  src/main/java/com/example/aboutme/converter/SpaceConverter.java
  src/main/java/com/example/aboutme/repository/SpaceRepository.java
  src/main/java/com/example/aboutme/service/SpaceService/SpaceQueryService.java
  src/main/java/com/example/aboutme/service/SpaceService/SpaceQueryServiceImpl.java
  src/main/java/com/example/aboutme/service/SpaceService/SpaceService.java
  src/main/java/com/example/aboutme/service/SpaceService/SpaceServiceImpl.java
  src/main/resources/application.yml
Labels: ✨ feat

#26 #25 브랜치 변경
  .github/workflows/dev-deploy.yaml
Labels: ❗️HOTFIX

#28 #25 javaVersion
  .github/workflows/dev-deploy.yaml
Labels: 🐛 fix

#30 #26 애플리케이션 이름
  .github/workflows/dev-deploy.yaml
Labels: 🚚 chore

#36 #35 deploy.yaml 문제 해결
  .github/workflows/dev-deploy.yaml
Labels: 🚚 chore

#40 #39 feat: health api 추가
  src/main/java/com/example/aboutme/app/controller/RootController.java
Labels: 🚚 chore

#13 #6 프로필 보관함 즐겨찾기 기능 구현
  .DS_Store
  src/main/java/com/example/aboutme/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/aboutme/app/controller/MemberProfileController.java
  src/main/java/com/example/aboutme/app/controller/MemberSpaceController.java
  src/main/java/com/example/aboutme/app/dto/MemberProfileResponse.java
  src/main/java/com/example/aboutme/app/dto/MemberSpaceResponse.java
  src/main/java/com/example/aboutme/converter/MemberProfileConverter.java
  src/main/java/com/example/aboutme/converter/MemberSpaceConverter.java
  src/main/java/com/example/aboutme/domain/mapping/MemberProfile.java
  src/main/java/com/example/aboutme/domain/mapping/MemberSpace.java
  src/main/java/com/example/aboutme/repository/MemberProfileRepository.java
  src/main/java/com/example/aboutme/repository/MemberRepository.java
  src/main/java/com/example/aboutme/repository/MemberSpaceRepository.java
  src/main/java/com/example/aboutme/repository/SpaceRepository.java
  src/main/java/com/example/aboutme/service/MemberProfileService/MemberProfileService.java
  src/main/java/com/example/aboutme/service/MemberProfileService/MemberProfileServiceImpl.java
  src/main/java/com/example/aboutme/service/MemberSpaceService/MemberSpaceService.java
  src/main/java/com/example/aboutme/service/MemberSpaceService/MemberSpaceServiceImpl.java
  src/main/resources/application.yml
Labels: ✨ feat

#11 #5 아지트 내 스페이스 기능 구현
  .DS_Store
  src/main/java/com/example/aboutme/app/controller/MemberSpaceController.java
  src/main/java/com/example/aboutme/app/dto/MemberSpaceResponse.java
  src/main/java/com/example/aboutme/domain/Space.java
  src/main/java/com/example/aboutme/domain/mapping/MemberSpace.java
  src/main/java/com/example/aboutme/repository/MemberRepository.java
  src/main/java/com/example/aboutme/repository/MemberSpaceRepository.java
  src/main/java/com/example/aboutme/repository/SpaceRepository.java
  src/main/java/com/example/aboutme/service/MemberSpaceService.java
Labels: ✨ feat

#37 #20 내 마이프로필 삭제 API 구현완료
  src/main/java/com/example/aboutme/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/aboutme/app/controller/ProfileController.java
  src/main/java/com/example/aboutme/service/ProfileService/ProfileService.java
  src/main/java/com/example/aboutme/service/ProfileService/ProfileServiceImpl.java
  src/main/java/com/example/aboutme/validation/annotation/ExistMyProfile.java
  src/main/java/com/example/aboutme/validation/validator/ProfileExistValidator.java
Labels: ✨ feat

#38 #21 마이프로필 3개 이상 생성되는 버그 해결
  src/main/java/com/example/aboutme/service/ProfileService/ProfileServiceImpl.java
Labels: 🐛 fix

#47 헤더명 언더스코어->하이픈으로 변경
  src/main/java/com/example/aboutme/app/controller/ProfileController.java
Labels: 🐛 fix

#51 #50 헤더 이름 변경 (언더스코어 → 하이픈)
  src/main/java/com/example/aboutme/app/controller/MemberProfileController.java
  src/main/java/com/example/aboutme/app/controller/MemberSpaceController.java
  src/main/java/com/example/aboutme/service/SpaceService/SpaceServiceImpl.java
Labels: 🚧 update

#55 #54 validation 커스텀 어노테이션 적용
  src/main/java/com/example/aboutme/app/controller/MemberProfileController.java
  src/main/java/com/example/aboutme/app/controller/MemberSpaceController.java
  src/main/java/com/example/aboutme/service/MemberProfileService/MemberProfileServiceImpl.java
  src/main/java/com/example/aboutme/service/MemberSpaceService/MemberSpaceServiceImpl.java
  src/main/java/com/example/aboutme/validation/annotation/ExistMySpace.java
  src/main/java/com/example/aboutme/validation/validator/SpaceExistValidator.java
Labels: 🚧 update

#52 #49 내 마이프로필 수정 API 구현 완료
  src/main/java/com/example/aboutme/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/aboutme/app/controller/ProfileController.java
  src/main/java/com/example/aboutme/app/dto/ProfileRequest.java
  src/main/java/com/example/aboutme/app/dto/ProfileResponse.java
  src/main/java/com/example/aboutme/converter/ProfileConverter.java
  src/main/java/com/example/aboutme/domain/ProfileFeature.java
  src/main/java/com/example/aboutme/repository/ProfileFeatureRepository.java
  src/main/java/com/example/aboutme/service/ProfileService/ProfileService.java
  src/main/java/com/example/aboutme/service/ProfileService/ProfileServiceImpl.java
  src/main/java/com/example/aboutme/validation/annotation/ExistProfileFeature.java
  src/main/java/com/example/aboutme/validation/validator/ProfileFeatureValidator.java
Labels: ✨ feat

#64 #63 !긴급 내 마이프로필 수정시 발생하던 에러 해결
  src/main/java/com/example/aboutme/service/ProfileService/ProfileServiceImpl.java
Labels: ❗️HOTFIX

#60 #59 내 마이프로필 단건 조회 API 구현완료
  src/main/java/com/example/aboutme/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/aboutme/app/controller/ProfileController.java
  src/main/java/com/example/aboutme/app/dto/ProfileResponse.java
  src/main/java/com/example/aboutme/converter/ProfileConverter.java
  src/main/java/com/example/aboutme/service/ProfileService/ProfileService.java
  src/main/java/com/example/aboutme/service/ProfileService/ProfileServiceImpl.java
Labels: ✨ feat

#62 #61 S3 파일 업로드 및 다운로드 API 구현
  build.gradle
  src/main/java/com/example/aboutme/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/aboutme/aws/s3/S3Config.java
  src/main/java/com/example/aboutme/aws/s3/S3Controller.java
  src/main/java/com/example/aboutme/aws/s3/S3ResponseDto.java
  src/main/java/com/example/aboutme/aws/s3/S3Service.java
  src/main/resources/application.yml
Labels: ✨ feat

#56 #53 상대방 마이프로필 내 보관함에 추가하기 API 구현 완료
  src/main/java/com/example/aboutme/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/aboutme/app/controller/ProfileController.java
  src/main/java/com/example/aboutme/app/dto/ProfileRequest.java
  src/main/java/com/example/aboutme/converter/MemberProfileConverter.java
  src/main/java/com/example/aboutme/repository/MemberProfileRepository.java
  src/main/java/com/example/aboutme/repository/ProfileRepository.java
  src/main/java/com/example/aboutme/service/MemberProfileService/MemberProfileService.java
  src/main/java/com/example/aboutme/service/MemberProfileService/MemberProfileServiceImpl.java
  src/main/java/com/example/aboutme/validation/annotation/ExistProfilesBySerialNum.java
  src/main/java/com/example/aboutme/validation/validator/ProfilesExistBySerialNumValidator.java
Labels: ✨ feat

#65 #41 마이스페이스 초기화하기
  src/main/java/com/example/aboutme/app/controller/SpaceController.java
  src/main/java/com/example/aboutme/repository/SpaceRepository.java
  src/main/java/com/example/aboutme/service/SpaceService/SpaceService.java
  src/main/java/com/example/aboutme/service/SpaceService/SpaceServiceImpl.java
  src/main/resources/application.yml
Labels: ✨ feat

#68 #67 빌드 에러 해결
  src/main/java/com/example/aboutme/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/aboutme/validation/validator/ProfileFeatureValidator.java
Labels: ❗️HOTFIX
